In [2]:
import pandas as pd

In [21]:
df = pd.read_csv('/Users/rahulbabu/Documents/SideProjects/Sniper Strategy bot/backtest-results/usdjpy-2025-01-06-to-13-fixed-10-persistent-entry/trade_signal_metrics_and_outcomes.csv')

In [25]:
df.head()

,trade_id,indicator_signal,direction,signal_price,entry_price,entry_bull_score,entry_bear_score,stop_price,tp1,tp2,...,bull_count,bear_count,signal_bull_score,signal_bear_score,market_bias,indicator_status,indicator_ready,exit_price,pnl_points,pnl_cash
0,1,SELL,SELL,15766.70,15766.70,0.000000,71.428571,15773.0,15760.4,15754.0,...,0,6,0.000000,85.714286,STRONG BEAR,SELL,True,15756.5,10.20,102.0
1,2,BUY,BUY,15768.45,15768.45,71.428571,0.000000,15760.9,15776.0,15783.6,...,6,1,85.714286,14.285714,STRONG BULL,BUY,True,15778.5,10.05,100.5
2,3,SELL,SELL,15740.65,15740.65,0.000000,85.714286,15755.0,15726.3,15711.9,...,0,7,0.000000,100.000000,STRONG BEAR,SELL,True,15730.5,10.15,101.5
3,4,BUY,BUY,15723.75,15723.75,71.428571,14.285714,15697.5,15750.0,15776.2,...,6,1,85.714286,14.285714,STRONG BULL,BUY,True,15713.6,-10.15,-101.5
4,5,SELL,SELL,15744.75,15744.75,14.285714,57.142857,15755.1,15734.4,15724.0,...,1,4,14.285714,57.142857,STRONG BEAR,SELL,True,15754.8,-10.05,-100.5

In [53]:
df[df.bear_count == 4]

,trade_id,indicator_signal,direction,signal_price,entry_price,entry_bull_score,entry_bear_score,stop_price,tp1,tp2,...,bull_count,bear_count,signal_bull_score,signal_bear_score,market_bias,indicator_status,indicator_ready,exit_price,pnl_points,pnl_cash
4,5,SELL,SELL,15744.75,15744.75,14.285714,57.142857,15755.1,15734.4,15724.0,...,1,4,14.285714,57.142857,STRONG BEAR,SELL,True,15754.8,-10.05,-100.5
15,16,SELL,SELL,15815.05,15815.05,14.285714,57.142857,15820.5,15809.6,15804.1,...,2,4,28.571429,57.142857,MILD BEAR,SELL,True,15804.4,10.65,106.5
17,18,SELL,SELL,15812.25,15812.25,14.285714,57.142857,15821.8,15802.7,15793.1,...,1,4,14.285714,57.142857,STRONG BEAR,SELL,True,15822.3,-10.05,-100.5
22,23,SELL,SELL,15834.30,15834.30,14.285714,57.142857,15842.9,15825.7,15817.1,...,2,4,28.571429,57.142857,MILD BEAR,SELL,True,15844.3,-10.00,-100.0
23,24,SELL,SELL,15836.65,15836.65,14.285714,57.142857,15845.0,15828.3,15820.0,...,1,4,14.285714,57.142857,STRONG BEAR,SELL,True,15846.7,-10.05,-100.5
24,25,SELL,SELL,15842.40,15842.40,14.285714,57.142857,15849.3,15835.5,15828.7,...,1,4,14.285714,57.142857,STRONG BEAR,SELL,True,15829.2,13.20,132.0

In [56]:
df.pnl_cash.describe()

count     46.000000
mean      -3.282609
std      118.880503
min     -370.000000
25%     -101.000000
50%        0.000000
75%      101.000000
max      198.500000
Name: pnl_cash, dtype: float64